CREATE DATABASE students;
USE students;
CREATE TABLE cse(
ROLLNO INT PRIMARY KEY,
NAME VARCHAR(50),
BRANCH VARCHAR(30),
MARKS INT,
AGE INT NOT NULL
);
INSERT INTO cse
(ROLLNO, NAME, BRANCH, MARKS, AGE)
VALUES
(28, "ANISH KUMAR", "CSE", 633, 17);

SELECT * FROM cse;
